name: customer_app
description: Production-ready Customer Management App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management & DI
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Navigation
  go_router: ^14.2.0

  # API
  dio: ^5.4.3+1

  # Secure Storage
  flutter_secure_storage: ^9.2.2

  # Local DB (Drift / SQLite)
  drift: ^2.18.0
# sqlite3_flutter_libs: ^0.5.27
  sqlite3_flutter_libs: ^0.6.0+eol
  path_provider: ^2.1.3
  path: ^1.9.0

  # Logging
  logger: ^2.3.0

  # Fonts
  google_fonts: ^6.2.1

  # Code Generation Annotations
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  drift_dev: ^2.18.0
  freezed: ^2.5.3
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.3

flutter:
  uses-material-design: true
